wandb_version: 1

exp_name:
  desc: null
  value: ppo_cleanrl
seed:
  desc: null
  value: 1
torch_deterministic:
  desc: null
  value: true
cuda:
  desc: null
  value: true
track:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: cleanRL
wandb_entity:
  desc: null
  value: null
capture_video:
  desc: null
  value: false
env_id:
  desc: null
  value: SuperMarioBros-1-1-v1
total_timesteps:
  desc: null
  value: 10000000
learning_rate:
  desc: null
  value: 0.00025
num_envs:
  desc: null
  value: 8
num_steps:
  desc: null
  value: 128
anneal_lr:
  desc: null
  value: true
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
num_minibatches:
  desc: null
  value: 4
update_epochs:
  desc: null
  value: 4
norm_adv:
  desc: null
  value: true
clip_coef:
  desc: null
  value: 0.1
clip_vloss:
  desc: null
  value: true
ent_coef:
  desc: null
  value: 0.01
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
target_kl:
  desc: null
  value: null
batch_size:
  desc: null
  value: 1024
minibatch_size:
  desc: null
  value: 256
num_iterations:
  desc: null
  value: 9765
_wandb:
  desc: null
  value:
    code_path: code/experimental/ppo_cleanrl.py
    python_version: 3.8.18
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707326857.874752
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.8.18
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
