site_name: "Hsuanwu"
site_url: https://docs.hsuanwu.dev/
copyright: Copyright &copy; 2023 Reinforcement Learning Evolution Foundation
theme:
  name: material
  logo: assets/images/icon.svg
  favicon: assets/images/icon.svg
  palette:
    - scheme: hsuanwu
      primary: hsuanwu
      accent: hsuanwu
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

repo_url: https://github.com/RLE-Foundation/Hsuanwu
repo_name: RLE-Foundation/Hsuanwu

extra:
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/RLE-Foundation/Hsuanwu
    - icon: fontawesome/solid/paper-plane
      link: friedrichyuan19990827@gmail.com
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/hsuanwu/
  
nav:
  - Overview: 
    - Overview: index.md
    - Changelog: changelog.md
    - Contribution: contributing.md
    - License: license.md

  - Getting Started:
    - Installation: getting_started.md
    - Verification: verification.md
  
  - Tutorials: tutorials.md

  - API Documentation:
    - Overview: overview/api.md
    - Common: 
      - Common Overview: overview/common_index/index.md
      - Engine: 
        - HsuanwuEngine: api/common/engine/__init__.md
        - BasePolicyTrainer: api/common/base_policy_trainer.md
        - OnPolicyTrainer: api/common/on_policy_trainer.md
        - OffPolicyTrainer: api/common/off_policy_trainer.md
        - DistributedTrainer: api/common/distributed_trainer.md
      - Logger: api/common/logger.md
      - Timer: api/common/timer.md

    - Xploit:
      - Xploit Overview: overview/xploit_index/index.md
      - agent:
        - BaseAgent: api/xploit/agent/base.md
        - SAC: api/xploit/agent/sac.md
        - DrQ: api/xploit/agent/sac.md
        - DrQv2: api/xploit/agent/drqv2.md
        - DDPG: api/xploit/agent/drqv2.md
        - PPG: api/xploit/agent/ppg.md
        - PPO: api/xploit/agent/ppo.md
        - DrAC: api/xploit/agent/ppo.md
        - IMPALA: api/xploit/agent/impala.md
      
      - encoder:
        - BaseEncoder: api/xploit/encoder/base.md
        - TassaCnnEncoder: api/xploit/encoder/tassa_cnn_encoder.md
        - MnihCnnEncoder: api/xploit/encoder/mnih_cnn_encoder.md
        - EspeholtResidualEncoder: api/xploit/encoder/espeholt_residual_encoder.md
        - VanillaMlpEncoder: api/xploit/encoder/vanilla_mlp_encoder.md
        - IdentityEncoder: api/xploit/encoder/identity_encoder.md

      - storage:
        - DistributedStorage: api/xploit/storage/distributed_storage.md
        - VanillaRolloutStorage: api/xploit/storage/vanilla_rollout_storage.md
        - VanillaReplayStorage: api/xploit/storage/vanilla_replay_storage.md
        - NStepReplayStorage: api/xploit/storage/nstep_replay_storage.md
        - PrioritizedReplayStorage: api/xploit/storage/prioritized_replay_storage.md

    - Xplore:
      - Xplore Overview: overview/xplore_index/index.md
      - reward:
        - BaseIntrinsicRewardModule: api/xplore/reward/base.md
        - PseudoCounts: api/xplore/reward/pseudo_counts.md
        - ICM: api/xplore/reward/icm.md
        - RND: api/xplore/reward/rnd.md
        - GIRM: api/xplore/reward/girm.md
        - NGU: api/xplore/reward/ngu.md
        - RIDE: api/xplore/reward/ride.md
        - RE3: api/xplore/reward/re3.md
        - RISE: api/xplore/reward/rise.md
        - REVD: api/xplore/reward/revd.md

      - augmentation:
        - BaseAugmentation: api/xplore/augmentation/base.md
        - ElasticTransform: api/xplore/augmentation/elastic_transform.md
        - GaussianNoise: api/xplore/augmentation/gaussian_noise.md
        - GrayScale: api/xplore/augmentation/grayscale.md
        - RandomAdjustSharpness: api/xplore/augmentation/random_adjustsharpness.md
        - RandomAmplitudeScaling: api/xplore/augmentation/random_amplitude_scaling.md
        - RandomAugment: api/xplore/augmentation/random_augment.md
        - RandomAutocontrast: api/xplore/augmentation/random_autocontrast.md
        - RandomColorJitter: api/xplore/augmentation/random_colorjitter.md
        - RandomConvolution: api/xplore/augmentation/random_convolution.md
        - RandomCrop: api/xplore/augmentation/random_crop.md
        - RandomCutout: api/xplore/augmentation/random_cutout.md
        - RandomCutoutColor: api/xplore/augmentation/random_cutoutcolor.md
        - RandomEqualize: api/xplore/augmentation/random_equalize.md
        - RandomFlip: api/xplore/augmentation/random_flip.md
        - RandomInvert: api/xplore/augmentation/random_invert.md
        - RandomPerspective: api/xplore/augmentation/random_perspective.md
        - RandomRotate: api/xplore/augmentation/random_rotate.md
        - RandomShift: api/xplore/augmentation/random_shift.md
        - RandomTranslate: api/xplore/augmentation/random_translate.md

      - distribution:
        - BaseDistribution: api/xplore/distribution/base.md
        - Categorical: api/xplore/distribution/categorical.md
        - DiagonalGaussian: api/xplore/distribution/diagonal_gaussian.md
        - SquashedNormal: api/xplore/distribution/squashed_normal.md
        - NormalNoise: api/xplore/distribution/truncated_normal_noise.md
        - OrnsteinUhlenbeckNoise: api/xplore/distribution/ornstein_uhlenbeck_noise.md
        - TruncatedNormalNoise: api/xplore/distribution/truncated_normal_noise.md
    
    - Env:
      - Env Overview: overview/env_index/index.md
      - make_atari_env: api/env/atari.md
      - make_bullet_env: api/env/bullet/__init__.md
      - make_dmc_env: api/env/dmc/__init__.md
      - make_procgen_env: api/env/procgen/__init__.md
      - make_minigrid_env: api/env/minigrid/__init__.md
      - utils:
        - HsuanwuEnvWrapper: api/env/utils.md
    
    - Evaluation:
      - Evaluation Overview: overview/evaluation_index/index.md
      - Comparison: api/evaluation/comparison.md
      - Performance: api/evaluation/performance.md

    - Pre-training: 
      - Pre-training Overview: overview/pretraining_index/index.md
    
    - Deployment: 
      - Deployment Overview: overview/deployment_index/index.md
  - Benchmarks: benchmarks.md