site_name: "Hsuanwu"
site_url: https://docs.hsuanwu.dev/
copyright: Copyright &copy; 2023 Reinforcement Learning Evolution Foundation
theme:
  name: material
  logo: assets/images/icon.svg
  favicon: assets/images/icon.svg
  palette:
    - scheme: hsuanwu
      primary: hsuanwu
      accent: hsuanwu
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

repo_url: https://github.com/BellmanProject/Hsuanwu
repo_name: BellmanProject/Hsuanwu

extra:
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/BellmanProject/Hsuanwu
    - icon: fontawesome/solid/paper-plane
      link: friedrichyuan19990827@gmail.com
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/hsuanwu/
  
nav:
  - Overview: 
    - Overview: index.md
    - Changelog: changelog.md
    - License: license.md

  - Getting Stared:
    - Installation: getting_started.md

  - API Documentation:
    - Overview: overview/api_overview.md
    - Common: 
      - Engine: 
        - BasePolicyTrainer: api/common/base_policy_trainer.md
        - OnPolicyTrainer: api/common/on_policy_trainer.md
        - OffPolicyTrainer: api/common/off_policy_trainer.md
      - Logger: api/common/logger.md
      - Timer: api/common/timer.md

    - Xploit:
      - Xploit Overview: overview/xploit_index/index.md
      - encoder:
        - BaseEncoder: api/xploit/encoder/base.md
        - VanillaCnnEncoder: api/xploit/encoder/vanilla_cnn_encoder.md
        - VanillaMlpEncoder: api/xploit/encoder/vanilla_mlp_encoder.md
        - ResNetEncoder: api/xploit/encoder/resnet_encoder.md
        - IdentityEncoder: api/xploit/encoder/identity_encoder.md

      - learner:
        - DrQv2Learner: api/xploit/learner/drqv2.md
        - PPGLearner: api/xploit/learner/ppg.md
        - PPOLearner: api/xploit/learner/ppo.md
        - DrACLearner: api/xploit/learner/drac.md
        - SACLearner: api/xploit/learner/sac.md
      
      - storage:
        - VanillaRolloutStorage: api/xploit/storage/vanilla_rollout_storage.md
        - VanillaReplayStorage: api/xploit/storage/vanilla_replay_storage.md
        - NStepReplayStorage: api/xploit/storage/nstep_replay_storage.md
        - PrioritizedReplayStorage: api/xploit/storage/prioritized_replay_storage.md

    - Xplore:
      - Xplore Overview: overview/xplore_index/index.md
      - reward:
        - BaseIntrinsicRewardModule: api/xplore/reward/base.md
        - ICM: api/xplore/reward/icm.md
        - RND: api/xplore/reward/rnd.md
        - GIRM: api/xplore/reward/girm.md
        - NGU: api/xplore/reward/ngu.md
        - RIDE: api/xplore/reward/ride.md
        - RE3: api/xplore/reward/re3.md
        - RISE: api/xplore/reward/rise.md
        - REVD: api/xplore/reward/revd.md

      - augmentation:
        - BaseAugmentation: api/xplore/augmentation/base.md
        - RandomColorJitter: api/xplore/augmentation/random_colorjitter.md
        - RandomConvolution: api/xplore/augmentation/random_convolution.md
        - RandomCrop: api/xplore/augmentation/random_crop.md
        - RandomCutout: api/xplore/augmentation/random_cutout.md
        - RandomCutoutColor: api/xplore/augmentation/random_cutoutcolor.md
        - RandomFlip: api/xplore/augmentation/random_flip.md
        - RandomRotate: api/xplore/augmentation/random_rotate.md
        - RandomShift: api/xplore/augmentation/random_shift.md
        - RandomTranslate: api/xplore/augmentation/random_translate.md

      - distribution:
        - BaseDistribution: api/xplore/distribution/base.md
        - Categorical: api/xplore/distribution/categorical.md
        - OrnsteinUhlenbeck: api/xplore/distribution/ornstein_uhlenbeck.md
        - SquashedNormal: api/xplore/distribution/squashed_normal.md
        - TruncatedNormal: api/xplore/distribution/truncated_normal.md
    
    - Env:
      - Overview: overview/env_index/index.md
      - make_atari_env: api/env/atari.md
      - make_dmc_env: api/env/dmc.md
      - make_procgen_env: api/env/procgen.md

    - Pre-training: 
      - Pre-training Overview: overview/pretraining_index/index.md
    
    - Deployment: 
      - Deployment Overview: overview/deployment_index/index.md
  - Benchmarks: benchmarks.md
