########################### Train setup
experiment: impala_atari
device: cuda:0            # Device (cpu, cuda, ...) on which the code should be run.
seed: 1                   # Random seed for reproduction.
num_train_steps: 30000000   # Number of training steps.

agent:
  name: IMPALA

hydra:
  run:
    dir: ./logs/${experiment}/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
  job:
    chdir: true