seed: 0 
device: cuda                            
use_aug: false                           
use_irs: false                           
num_train_steps: 10000000                                      
num_steps: 256
num_envs: 64
# test setup
test_every_episodes: 10
num_test_episodes: 10                

encoder:
  _target_: ResNetEncoder
  feature_dim: 256  

learner:
  _target_: PPOLearner

storage:
  _target_: VanillaRolloutStorage
  

distribution:
  _target_: Categorical

##############################################################
augmentation:
  _target_: RandomShift

##############################################################
reward:
  _target_: RE3

##############################################################
hydra:
  run:
    dir: ./logs/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  job:
    chdir: true