########################### Train setup
experiment: sac_dmc_pixel
device: cuda:0            # Device (cpu, cuda, ...) on which the code should be run.
seed: 1                   # Random seed for reproduction.
num_train_steps: 1000000   # Number of training steps.

learner:
  name: SACLearner

use_aug: true
encoder:
  name: TassaCnnEncoder
  feature_dim: 50

storage:
  name: PrioritizedReplayStorage

augmentation:
  name: RandomShift

hydra:
  run:
    dir: ./logs/${experiment}/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
  job:
    chdir: true